export * from './Button'
export * from './Spinner'
export { Text } from './Text'
export { Heading } from './Heading'
export { Label } from './Label'
export { default as config } from '../tamagui.config'
