export { Button, ButtonComponent } from './src/Button'
export { Text } from './src/Text'
export { Heading } from './src/Heading'
export { Label } from './src/Label'
export { Checkbox } from './src/Checkbox'
export { default as config } from './tamagui.config'
