export { Button } from './src/Button'
export { Spinner } from './src/Spinner'
export { Text } from './src/Text'
export { Heading } from './src/Heading'
export { Label } from './src/Label'
export { default as config } from './tamagui.config'
